name: "Build (Windows)"
permissions:
  contents: read
  artifact-metadata: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      artifact-metadata: write

    defaults:
      run:
        shell: msys2 {0}

    steps:

      - name: OS setup
        uses: msys2/setup-msys2@v2
        with:
          install: libzstd-devel git curl patch mingw-w64-x86_64-readline mingw-w64-x86_64-sbcl mingw-w64-x86_64-sbcl mingw-w64-x86_64-toolchain mingw-w64-x86_64-zstd mingw-w64-x86_64-openssl mingw-w64-x86_64-autotools

      - name: Checkout build scripts
        uses: actions/checkout@v6

      - name: Read build.env
        id: buildenv
        uses: falti/dotenv-action@f4656c46de6bc223dda660f6724d52537bc0642a # v1.1.5
        with:
          path: build.env
          export-variables: true
          keys-case: upper
          log-variables: true

      - name: Setup build environment
        run: |
          CUSTOM_LIBDIR="${GITHUB_WORKSPACE}/static_libs"
          mkdir -vp "${CUSTOM_LIBDIR}"
          echo "CUSTOM_LIBDIR=${CUSTOM_LIBDIR}" >> "${GITHUB_ENV}"

      - name: Checkout SBCL
        uses: actions/checkout@v6
        with:
          repository: sbcl/sbcl
          ref: "sbcl-${{env.SBCL_VERSION}}"
          path: sbcl

      - name: Patch SBCL
        run: cd sbcl && patch -p1 -i ../sbcl-customizations.patch

      - name: Build SBCL
        run: scripts/build_sbcl.sh "${{env.SBCL_HOST}}" "${{env.SBCL_VERSION}}" "${{env.ASDF_VERSION}}" "${{env.REVISION}}" "${{env.CUSTOM_LIBDIR}}"

      - name: Export build.env
        run: |
          echo "OPENSSL_VERSION=$(pacman -Q mingw-w64-x86_64-openssl | cut -d' ' -f2)" >> ${GITHUB_ENV}
          echo "REVISION=${{steps.buildenv.outputs.revision}}" >> ${GITHUB_ENV}
          cat > windows-${{ runner.arch }}.md << EOF

          **Windows ($(uname -m)):**

          - OpenSSL ${OPENSSL_VERSION}

          EOF

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v6
        with:
          name: tarballs-windows-${{ runner.arch }}
          path: |
            ${{env.SRCDIST}}
            ${{env.BINDIST}}
            windows-${{ runner.arch }}.md
          retention-days: 5
