name: "Build (Linux)"
permissions:
  contents: read
  artifact-metadata: read

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    container: ghcr.io/digikar99/oldglibc-openssl35-commonlisp:glibc_2_28
    permissions:
      artifact-metadata: write
    steps:
      - name: OS setup
        run: |
          yum -y install dnf-plugins-core
          yum -y install git make perl check-devel texinfo check wget
          case "$(uname -m)" in
            x86_64) GH_ARCH=amd64
               ;;
            aarch64) GH_ARCH=arm64
               ;;
            *) echo "Unsupported architecture: $(uname -m)" >&2
               exit 1
               ;;
          esac

          GH_VERSION=2.101.0
          wget "https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_${GH_ARCH}.rpm"
          yum -y install "gh_${GH_VERSION}_linux_${GH_ARCH}.rpm"
          rm "gh_${GH_VERSION}_linux_${GH_ARCH}.rpm"

      - name: Checkout build scripts
        uses: actions/checkout@v7

      - name: Read build.env
        id: buildenv
        uses: falti/dotenv-action@f4656c46de6bc223dda660f6724d52537bc0642a # v1.1.5
        with:
          path: build.env
          export-variables: true
          keys-case: upper
          log-variables: true

      - name: Setup build environment
        run: |
          CUSTOM_LIBDIR="${GITHUB_WORKSPACE}/static_libs"
          mkdir -vp "${CUSTOM_LIBDIR}"
          echo "CUSTOM_LIBDIR=${CUSTOM_LIBDIR}" >> "${GITHUB_ENV}"

      - name: Checkout and build libfixposix
        run: |
          git clone --depth 1 https://github.com/sionescu/libfixposix
          scripts/build_libfixposix.sh "${{env.CUSTOM_LIBDIR}}"

      - name: Checkout SBCL
        uses: actions/checkout@v7
        with:
          repository: sbcl/sbcl
          ref: "sbcl-${{env.SBCL_VERSION}}"
          path: sbcl

      - name: Patch SBCL
        run: cd sbcl && patch -p1 -i ../sbcl-customizations.patch

      - name: Build SBCL
        run: |
          scripts/build_sbcl.sh "sbcl" "${{env.SBCL_VERSION}}" "${{env.ASDF_VERSION}}" "${{env.REVISION}}" "${{env.CUSTOM_LIBDIR}}"

      - name: Export build.env
        run: |
          LIBFIXPOSIX_VERSION=${{steps.buildenv.outputs.libfixposix_version}}

          export PKG_CONFIG_PATH="/hbb_exe/lib64/pkgconfig:/hbb_exe/lib/pkgconfig:$PKG_CONFIG_PATH"
          OPENSSL_VERSION=$(pkg-config --modversion openssl)

          LIBTLS_VERSION="${{ env.LIBTLS_VERSION }}"
          cat > linux-${{ runner.arch }}.md << EOF

          **Linux ($(uname -m))**

          - libfixposix ${LIBFIXPOSIX_VERSION}
          - OpenSSL ${OPENSSL_VERSION}
          - LibTLS ${LIBTLS_VERSION}

          EOF

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v7
        with:
          name: tarballs-linux-${{ runner.arch }}
          path: |
            ${{env.SRCDIST}}
            ${{env.BINDIST}}
            linux-${{ runner.arch }}.md
          retention-days: 5
